# Crear una nueva factura
POST http://localhost:9000/api/facturas
Content-Type: application/json

{
  "id_factura": 1,
  "monto": "1000",
  "fecha_emision": "2024-11-26T10:00:00Z",
  "fecha_vencimiento": "2024-12-10T10:00:00Z",
  "estado": "sin cancelar",
  "metodo_pago": "efectivo",
  "id_proceso": 1
}

###

# Editar una factura
PUT http://localhost:9000/api/facturas/1
Content-Type: application/json

{
  "monto": "1200",
  "fecha_emision": "2024-11-26T10:00:00Z",
  "fecha_vencimiento": "2024-12-10T10:00:00Z",
  "estado": "cancelada",
  "metodo_pago": "transferencia",
  "id_proceso": 2
}

###


# Obtener una factura por ID
GET http://localhost:9000/api/facturas/1
Content-Type: application/json

###

# Obtener todas las facturas con filtros opcionales (estado, metodo_pago, id_proceso)
GET http://localhost:9000/api/facturas
Content-Type: application/json

###

# Eliminar una factura por ID
DELETE http://localhost:9000/api/facturas/1
Content-Type: application/json

###
